version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql_data

  adminer:
      container_name: my_adminer
      image: adminer
      restart: always
      depends_on:
        - db
      ports:
        - 8080:8080
